# Generated by Django 4.0.5 on 2022-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavitustore', '0002_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
