# Generated by Django 4.0.5 on 2022-06-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mavitustore', '0003_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
